"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import MyClass

# Implementing MyFrame1
class MyProject1MyFrame1( MyClass.MyFrame1 ):
	def __init__( self, parent ):
		MyClass.MyFrame1.__init__( self, parent )

	# Handlers for MyFrame1 events.
	def URL( self, event ):
		# TODO: Implement URL
		pass

	def page( self, event ):
		# TODO: Implement page
		pass

	def word( self, event ):
		# TODO: Implement word
		pass

	def csv( self, event ):
		# TODO: Implement csv
		pass


